"""Add created_at to aggregation_batch

Revision ID: 004ad61da81c
Revises: enforce_single_aggregation
Create Date: 2026-01-09 22:54:02.886022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004ad61da81c'
down_revision: Union[str, Sequence[str], None] = 'enforce_single_aggregation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregation_goats')
    op.add_column('aggregation_batch', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('fk_goat_aggregation_batch'), 'goat', type_='foreignkey')
    op.create_foreign_key(None, 'goat', 'aggregation_batch', ['aggregation_batch_id'], ['id'])
    op.add_column('processing_batch', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_batch', 'created_at')
    op.drop_constraint(None, 'goat', type_='foreignkey')
    op.create_foreign_key(op.f('fk_goat_aggregation_batch'), 'goat', 'aggregation_batch', ['aggregation_batch_id'], ['id'], ondelete='SET NULL')
    op.drop_column('aggregation_batch', 'created_at')
    op.create_table('aggregation_goats',
    sa.Column('goat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregation_batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], name=op.f('aggregation_goats_aggregation_batch_id_fkey')),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], name=op.f('aggregation_goats_goat_id_fkey'))
    )
    # ### end Alembic commands ###