"""Initial baseline

Revision ID: 88bbcc348268
Revises: 
Create Date: 2026-01-09 21:51:32.846757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88bbcc348268'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS aggregation_goats CASCADE")
    op.add_column('aggregation_batch', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('goat', sa.Column('aggregation_batch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goat', 'aggregation_batch', ['aggregation_batch_id'], ['id'])
    op.add_column('processing_batch', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_batch', 'created_at')
    op.drop_constraint(None, 'goat', type_='foreignkey')
    op.drop_column('goat', 'aggregation_batch_id')
    op.drop_column('aggregation_batch', 'created_at')
    op.create_table('aggregation_goats',
    sa.Column('goat_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregation_batch_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], name=op.f('aggregation_goats_aggregation_batch_id_fkey')),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], name=op.f('aggregation_goats_goat_id_fkey'))
    )
    # ### end Alembic commands ###
