from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ImpactMetricDefinition:
    code: str
    name: str
    category: str
    unit: str
    source_module: str
    description: str


IMPACT_METRICS: dict[str, ImpactMetricDefinition] = {
    "pastoralists_onboarded": ImpactMetricDefinition(
        "pastoralists_onboarded",
        "Pastoralists Onboarded",
        "livestock_supply",
        "people",
        "farmers",
        "Farmer profiles onboarded into Rizara's supply network.",
    ),
    "animals_procured": ImpactMetricDefinition(
        "animals_procured",
        "Animals Procured",
        "livestock_supply",
        "head",
        "procurement",
        "Animals captured through procurement records.",
    ),
    "animals_aggregated": ImpactMetricDefinition(
        "animals_aggregated",
        "Animals Aggregated",
        "livestock_operations",
        "head",
        "aggregation",
        "Animals linked to aggregation batches.",
    ),
    "animals_processed": ImpactMetricDefinition(
        "animals_processed",
        "Animals Processed",
        "livestock_operations",
        "head",
        "processing",
        "Animals linked to processing batches.",
    ),
    "animals_traced": ImpactMetricDefinition(
        "animals_traced",
        "Animals Traced",
        "traceability",
        "head",
        "traceability",
        "Traceability records generated for animals.",
    ),
    "traceability_coverage_percent": ImpactMetricDefinition(
        "traceability_coverage_percent",
        "Traceability Coverage",
        "traceability",
        "%",
        "traceability",
        "Animal traceability record coverage as a percentage of animals in the platform.",
    ),
    "active_grants": ImpactMetricDefinition(
        "active_grants",
        "Active Grants",
        "institutional_grants",
        "applications",
        "grants",
        "Grant applications under active execution or review.",
    ),
    "awarded_grants": ImpactMetricDefinition(
        "awarded_grants",
        "Awarded Grants",
        "institutional_grants",
        "applications",
        "grants",
        "Grant applications marked awarded.",
    ),
    "overdue_reports": ImpactMetricDefinition(
        "overdue_reports",
        "Overdue Reports",
        "institutional_grants",
        "reports",
        "grants",
        "Grant reports past due and not accepted or submitted.",
    ),
    "active_projects": ImpactMetricDefinition(
        "active_projects",
        "Active Strategic Projects",
        "strategic_execution",
        "projects",
        "projects",
        "Active strategic projects in institutional execution.",
    ),
    "invoices_generated": ImpactMetricDefinition(
        "invoices_generated",
        "Invoices Generated",
        "commercial",
        "invoices",
        "invoices",
        "Invoices generated by Rizara commercial workflows.",
    ),
    "total_sales_value": ImpactMetricDefinition(
        "total_sales_value",
        "Total Sales Value",
        "commercial",
        "currency",
        "invoices",
        "Total invoice value excluding void invoices.",
    ),
    "goat_carcass_kg": ImpactMetricDefinition(
        "goat_carcass_kg",
        "Goat Carcass Weight",
        "processing_yield",
        "kg",
        "processing",
        "Recorded goat carcass yield.",
    ),
    "sheep_carcass_kg": ImpactMetricDefinition(
        "sheep_carcass_kg",
        "Sheep Carcass Weight",
        "processing_yield",
        "kg",
        "processing",
        "Recorded sheep carcass yield.",
    ),
    "cattle_carcass_kg": ImpactMetricDefinition(
        "cattle_carcass_kg",
        "Cattle Carcass Weight",
        "processing_yield",
        "kg",
        "processing",
        "Recorded cattle carcass yield.",
    ),
}


def metric_codes() -> set[str]:
    return set(IMPACT_METRICS)
