"""Add county and ward to farmer

Revision ID: 00ae7e360659
Revises: 099e0f9ff867
Create Date: 2026-01-07 21:43:58.633482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ae7e360659'
down_revision = '099e0f9ff867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('county', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ward', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_column('ward')
        batch_op.drop_column('county')

    # ### end Alembic commands ###
