"""initial rizara traceability schema

Revision ID: 099e0f9ff867
Revises: 
Create Date: 2026-01-07 14:51:54.685969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '099e0f9ff867'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('processing_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility', sa.String(length=120), nullable=False),
    sa.Column('slaughter_date', sa.Date(), nullable=True),
    sa.Column('halal_cert_ref', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goat',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('aggregation_goats',
    sa.Column('aggregation_id', sa.Integer(), nullable=True),
    sa.Column('goat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['aggregation_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], )
    )
    op.create_table('processing_goats',
    sa.Column('processing_id', sa.Integer(), nullable=True),
    sa.Column('goat_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], ),
    sa.ForeignKeyConstraint(['processing_id'], ['processing_batch.id'], )
    )
    op.create_table('traceability_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goat_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('public_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traceability_record')
    op.drop_table('processing_goats')
    op.drop_table('aggregation_goats')
    op.drop_table('goat')
    op.drop_table('user')
    op.drop_table('processing_batch')
    op.drop_table('farmer')
    op.drop_table('aggregation_batch')
    # ### end Alembic commands ###
