"""Add locking to aggregation and processing batches

Revision ID: 347974a21ee8
Revises: 00ae7e360659
Create Date: 2026-01-08 17:43:43.569038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347974a21ee8'
down_revision = '00ae7e360659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregation_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('aggregation_goats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_batch_id', sa.Integer(), nullable=False))
        batch_op.alter_column('goat_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('aggregation_goats_aggregation_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'aggregation_batch', ['aggregation_batch_id'], ['id'])
        batch_op.drop_column('aggregation_id')

    with op.batch_alter_table('processing_batch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_locked', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('processing_goats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_batch_id', sa.Integer(), nullable=False))
        batch_op.alter_column('goat_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('processing_goats_processing_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'processing_batch', ['processing_batch_id'], ['id'])
        batch_op.drop_column('processing_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_goats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('processing_goats_processing_id_fkey'), 'processing_batch', ['processing_id'], ['id'])
        batch_op.alter_column('goat_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('processing_batch_id')

    with op.batch_alter_table('processing_batch', schema=None) as batch_op:
        batch_op.drop_column('locked_at')
        batch_op.drop_column('is_locked')

    with op.batch_alter_table('aggregation_goats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aggregation_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('aggregation_goats_aggregation_id_fkey'), 'aggregation_batch', ['aggregation_id'], ['id'])
        batch_op.alter_column('goat_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_column('aggregation_batch_id')

    with op.batch_alter_table('aggregation_batch', schema=None) as batch_op:
        batch_op.drop_column('locked_at')
        batch_op.drop_column('is_locked')

    # ### end Alembic commands ###
