"""initial schema

Revision ID: 3f729753c9d3
Revises: 
Create Date: 2026-01-17 12:49:35.038780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f729753c9d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregation_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_notes', sa.String(length=255), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('order_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_location', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('facility', sa.String(length=120), nullable=False),
    sa.Column('slaughter_date', sa.Date(), nullable=True),
    sa.Column('halal_cert_ref', sa.String(length=120), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traceability_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('public_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cattle',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('goat',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('sheep',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('processing_cattle',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'cattle_id')
    )
    op.create_table('processing_goats',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('goat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'goat_id')
    )
    op.create_table('processing_sheep',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('sheep_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.ForeignKeyConstraint(['sheep_id'], ['sheep.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'sheep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_sheep')
    op.drop_table('processing_goats')
    op.drop_table('processing_cattle')
    op.drop_table('sheep')
    op.drop_table('goat')
    op.drop_table('cattle')
    op.drop_table('user')
    op.drop_table('traceability_record')
    op.drop_table('processing_batch')
    op.drop_table('order_requests')
    op.drop_table('farmer')
    op.drop_table('contact_messages')
    op.drop_table('aggregation_batch')
    # ### end Alembic commands ###
