"""initial baseline

Revision ID: ca0a3f3f842f
Revises: 
Create Date: 2026-01-21 12:34:33.858269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0a3f3f842f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('expense_class', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_notes', sa.String(length=255), nullable=True),
    sa.Column('onboarded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('traceability_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_data', sa.Text(), nullable=False),
    sa.Column('public_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregation_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('date_received', sa.Date(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('performed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('from_farmer_id', sa.Integer(), nullable=True),
    sa.Column('to_farmer_id', sa.Integer(), nullable=True),
    sa.Column('from_location', sa.String(length=120), nullable=True),
    sa.Column('to_location', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by_user_id', sa.Integer(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_farmer_id'], ['farmer.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_farmer_id'], ['farmer.id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('asset_type', sa.String(length=60), nullable=False),
    sa.Column('ownership_type', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tax_pin', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_method', sa.String(length=30), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('cost_center', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['expense_category.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('facility', sa.String(length=120), nullable=False),
    sa.Column('slaughter_date', sa.Date(), nullable=True),
    sa.Column('halal_cert_ref', sa.String(length=120), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregation_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('incurred_date', sa.Date(), nullable=False),
    sa.Column('paid_to', sa.String(length=120), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_health_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_type', sa.String(length=20), nullable=False),
    sa.Column('animal_id', sa.UUID(), nullable=False),
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=200), nullable=True),
    sa.Column('treatment', sa.String(length=200), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('treated_by', sa.String(length=120), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cattle',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('aggregated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('live_weight_kg', sa.Float(), nullable=True),
    sa.Column('weight_method', sa.String(length=20), nullable=True),
    sa.Column('purchase_price_per_head', sa.Float(), nullable=True),
    sa.Column('purchase_currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['aggregated_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('goat',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('aggregated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('live_weight_kg', sa.Float(), nullable=True),
    sa.Column('weight_method', sa.String(length=20), nullable=True),
    sa.Column('purchase_price_per_head', sa.Float(), nullable=True),
    sa.Column('purchase_currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['aggregated_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('order_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('product', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_location', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_batch_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('total_sale_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_batch_id')
    )
    op.create_table('processing_yield',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('total_carcass_weight_kg', sa.Float(), nullable=False),
    sa.Column('parts_included_in_batch_sale', sa.Boolean(), nullable=False),
    sa.Column('parts_sold_separately', sa.Boolean(), nullable=False),
    sa.Column('parts_notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('processing_batch_id')
    )
    op.create_table('sheep',
    sa.Column('aggregation_batch_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('farmer_tag', sa.String(length=64), nullable=False),
    sa.Column('rizara_id', sa.String(length=64), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('estimated_dob', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('aggregated_at', sa.DateTime(), nullable=True),
    sa.Column('aggregated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('live_weight_kg', sa.Float(), nullable=True),
    sa.Column('weight_method', sa.String(length=20), nullable=True),
    sa.Column('purchase_price_per_head', sa.Float(), nullable=True),
    sa.Column('purchase_currency', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['aggregated_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['aggregation_batch_id'], ['aggregation_batch.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rizara_id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=40), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('processing_batch_sale_id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'issued', 'paid', 'void', name='invoice_status', native_enum=False), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_sale_id'], ['processing_batch_sale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('processing_batch_sale_id')
    )
    op.create_table('processing_cattle',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'cattle_id')
    )
    op.create_table('processing_goats',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('goat_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['goat_id'], ['goat.id'], ),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'goat_id')
    )
    op.create_table('processing_sheep',
    sa.Column('processing_batch_id', sa.Integer(), nullable=False),
    sa.Column('sheep_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['processing_batch_id'], ['processing_batch.id'], ),
    sa.ForeignKeyConstraint(['sheep_id'], ['sheep.id'], ),
    sa.PrimaryKeyConstraint('processing_batch_id', 'sheep_id')
    )
    op.create_table('invoice_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_item')
    op.drop_table('processing_sheep')
    op.drop_table('processing_goats')
    op.drop_table('processing_cattle')
    op.drop_table('invoice')
    op.drop_table('sheep')
    op.drop_table('processing_yield')
    op.drop_table('processing_batch_sale')
    op.drop_table('order_requests')
    op.drop_table('goat')
    op.drop_table('cattle')
    op.drop_table('asset_maintenance')
    op.drop_table('animal_health_event')
    op.drop_table('aggregation_cost')
    op.drop_table('processing_batch')
    op.drop_table('expense')
    op.drop_table('buyer')
    op.drop_table('asset')
    op.drop_table('animal_event')
    op.drop_table('aggregation_batch')
    op.drop_table('vendor')
    op.drop_table('user')
    op.drop_table('traceability_record')
    op.drop_table('farmer')
    op.drop_table('expense_category')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
